name: main

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

env:
  EMAIL: ${{ secrets.EMAIL }}
  USERNAME: ${{ secrets.USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - run: npm ci
      - name: Generate README
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: npm run generate
      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
      - name: Update README.md
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Update README.md"
          git push
