name: main

on:
  workflow_dispatch:
  schedule:
  - cron: "*/15 * * * *"

env:
  EMAIL: ${{ secrets.EMAIL }}
  USERNAME: ${{ secrets.USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.16.1
    - run: npm ci
    - name: Generate README
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: npm run generate
    - name: Update README.md
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
        git stash
        git pull
        git stash pop
        git add .
        git commit -m "Update README.md" || echo "Nothing changes"
        git push
